# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:/studioTools/tools/sceneCollector/ui.ui'
#
# Created: Fri Mar 25 18:43:21 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AssetCollectorWin(object):
    def setupUi(self, AssetCollectorWin):
        AssetCollectorWin.setObjectName("AssetCollectorWin")
        AssetCollectorWin.resize(1054, 586)
        self.centralwidget = QtGui.QWidget(AssetCollectorWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.shot_listWidget = QtGui.QListWidget(self.centralwidget)
        self.shot_listWidget.setObjectName("shot_listWidget")
        self.verticalLayout.addWidget(self.shot_listWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.addShot_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.addShot_lineEdit.setObjectName("addShot_lineEdit")
        self.horizontalLayout_2.addWidget(self.addShot_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.loadShot_pushButton = QtGui.QPushButton(self.centralwidget)
        self.loadShot_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadShot_pushButton.setObjectName("loadShot_pushButton")
        self.verticalLayout.addWidget(self.loadShot_pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.asset_listWidget = QtGui.QListWidget(self.centralwidget)
        self.asset_listWidget.setObjectName("asset_listWidget")
        self.verticalLayout_2.addWidget(self.asset_listWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.allShot_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.allShot_checkBox.setObjectName("allShot_checkBox")
        self.horizontalLayout_10.addWidget(self.allShot_checkBox)
        self.autoCopy_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.autoCopy_checkBox.setObjectName("autoCopy_checkBox")
        self.horizontalLayout_10.addWidget(self.autoCopy_checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.loadAsset_pushButton = QtGui.QPushButton(self.centralwidget)
        self.loadAsset_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadAsset_pushButton.setObjectName("loadAsset_pushButton")
        self.verticalLayout_2.addWidget(self.loadAsset_pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.copy_listWidget = QtGui.QListWidget(self.centralwidget)
        self.copy_listWidget.setObjectName("copy_listWidget")
        self.verticalLayout_6.addWidget(self.copy_listWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.dst_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.dst_lineEdit.setObjectName("dst_lineEdit")
        self.horizontalLayout.addWidget(self.dst_lineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.copy_pushButton = QtGui.QPushButton(self.centralwidget)
        self.copy_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.copy_pushButton.setObjectName("copy_pushButton")
        self.verticalLayout_6.addWidget(self.copy_pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        AssetCollectorWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AssetCollectorWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 21))
        self.menubar.setObjectName("menubar")
        AssetCollectorWin.setMenuBar(self.menubar)

        self.retranslateUi(AssetCollectorWin)
        QtCore.QMetaObject.connectSlotsByName(AssetCollectorWin)

    def retranslateUi(self, AssetCollectorWin):
        AssetCollectorWin.setWindowTitle(QtGui.QApplication.translate("AssetCollectorWin", "Asset Collector", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AssetCollectorWin", "File List : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AssetCollectorWin", "Add file : ", None, QtGui.QApplication.UnicodeUTF8))
        self.loadShot_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Load Shot List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AssetCollectorWin", "Asset List : ", None, QtGui.QApplication.UnicodeUTF8))
        self.allShot_checkBox.setText(QtGui.QApplication.translate("AssetCollectorWin", "All Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.autoCopy_checkBox.setText(QtGui.QApplication.translate("AssetCollectorWin", "Automatic copy after load", None, QtGui.QApplication.UnicodeUTF8))
        self.loadAsset_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Load Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AssetCollectorWin", "Destination files : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AssetCollectorWin", "Destination : ", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Copy", None, QtGui.QApplication.UnicodeUTF8))

