# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'O:\studioTools\tools\sceneCollector\ui.ui'
#
# Created: Fri Jul 22 15:06:01 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from qtshim import QtCore, QtGui
from qtshim import Signal
from qtshim import wrapinstance


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AssetCollectorWin(object):
    def setupUi(self, AssetCollectorWin):
        AssetCollectorWin.setObjectName(_fromUtf8("AssetCollectorWin"))
        AssetCollectorWin.resize(1054, 586)
        self.centralwidget = QtGui.QWidget(AssetCollectorWin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.shot_listWidget = QtGui.QListWidget(self.centralwidget)
        self.shot_listWidget.setAlternatingRowColors(True)
        self.shot_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.shot_listWidget.setObjectName(_fromUtf8("shot_listWidget"))
        self.verticalLayout.addWidget(self.shot_listWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.addShot_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.addShot_lineEdit.setObjectName(_fromUtf8("addShot_lineEdit"))
        self.horizontalLayout_2.addWidget(self.addShot_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.loadMultipleShot_pushButton = QtGui.QPushButton(self.centralwidget)
        self.loadMultipleShot_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadMultipleShot_pushButton.setObjectName(_fromUtf8("loadMultipleShot_pushButton"))
        self.horizontalLayout_4.addWidget(self.loadMultipleShot_pushButton)
        self.loadShot_pushButton = QtGui.QPushButton(self.centralwidget)
        self.loadShot_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadShot_pushButton.setObjectName(_fromUtf8("loadShot_pushButton"))
        self.horizontalLayout_4.addWidget(self.loadShot_pushButton)
        self.removeList_pushButton = QtGui.QPushButton(self.centralwidget)
        self.removeList_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.removeList_pushButton.setObjectName(_fromUtf8("removeList_pushButton"))
        self.horizontalLayout_4.addWidget(self.removeList_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.loadAsset_pushButton = QtGui.QPushButton(self.centralwidget)
        self.loadAsset_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.loadAsset_pushButton.setObjectName(_fromUtf8("loadAsset_pushButton"))
        self.verticalLayout.addWidget(self.loadAsset_pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.info_label = QtGui.QLabel(self.centralwidget)
        self.info_label.setObjectName(_fromUtf8("info_label"))
        self.horizontalLayout_3.addWidget(self.info_label)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.asset_tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.asset_tableWidget.setAlternatingRowColors(True)
        self.asset_tableWidget.setObjectName(_fromUtf8("asset_tableWidget"))
        self.asset_tableWidget.setColumnCount(6)
        self.asset_tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.asset_tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.asset_tableWidget)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.allShot_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.allShot_checkBox.setObjectName(_fromUtf8("allShot_checkBox"))
        self.horizontalLayout_10.addWidget(self.allShot_checkBox)
        self.assembly_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.assembly_checkBox.setChecked(True)
        self.assembly_checkBox.setObjectName(_fromUtf8("assembly_checkBox"))
        self.horizontalLayout_10.addWidget(self.assembly_checkBox)
        self.autoCopy_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.autoCopy_checkBox.setObjectName(_fromUtf8("autoCopy_checkBox"))
        self.horizontalLayout_10.addWidget(self.autoCopy_checkBox)
        self.autoSave_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.autoSave_checkBox.setChecked(True)
        self.autoSave_checkBox.setObjectName(_fromUtf8("autoSave_checkBox"))
        self.horizontalLayout_10.addWidget(self.autoSave_checkBox)
        self.save_pushButton = QtGui.QPushButton(self.centralwidget)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.horizontalLayout_10.addWidget(self.save_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.dst_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.dst_lineEdit.setObjectName(_fromUtf8("dst_lineEdit"))
        self.horizontalLayout.addWidget(self.dst_lineEdit)
        self.checkPath_pushButton = QtGui.QPushButton(self.centralwidget)
        self.checkPath_pushButton.setObjectName(_fromUtf8("checkPath_pushButton"))
        self.horizontalLayout.addWidget(self.checkPath_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.copy_pushButton = QtGui.QPushButton(self.centralwidget)
        self.copy_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.copy_pushButton.setObjectName(_fromUtf8("copy_pushButton"))
        self.verticalLayout_2.addWidget(self.copy_pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        AssetCollectorWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AssetCollectorWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        AssetCollectorWin.setMenuBar(self.menubar)

        self.retranslateUi(AssetCollectorWin)
        QtCore.QMetaObject.connectSlotsByName(AssetCollectorWin)

    def retranslateUi(self, AssetCollectorWin):
        AssetCollectorWin.setWindowTitle(QtGui.QApplication.translate("AssetCollectorWin", "Asset Collector", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AssetCollectorWin", "File List : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AssetCollectorWin", "Add file : ", None, QtGui.QApplication.UnicodeUTF8))
        self.loadMultipleShot_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Load Multiple Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.loadShot_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Load Shot List", None, QtGui.QApplication.UnicodeUTF8))
        self.removeList_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Remove List", None, QtGui.QApplication.UnicodeUTF8))
        self.loadAsset_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Load Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AssetCollectorWin", "Asset List : ", None, QtGui.QApplication.UnicodeUTF8))
        self.info_label.setText(QtGui.QApplication.translate("AssetCollectorWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        item = self.asset_tableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("AssetCollectorWin", "File Type", None, QtGui.QApplication.UnicodeUTF8))
        item = self.asset_tableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("AssetCollectorWin", "File Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.asset_tableWidget.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("AssetCollectorWin", "Status", None, QtGui.QApplication.UnicodeUTF8))
        item = self.asset_tableWidget.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("AssetCollectorWin", "No", None, QtGui.QApplication.UnicodeUTF8))
        item = self.asset_tableWidget.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("AssetCollectorWin", "Source Path", None, QtGui.QApplication.UnicodeUTF8))
        item = self.asset_tableWidget.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("AssetCollectorWin", "Copy Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.allShot_checkBox.setText(QtGui.QApplication.translate("AssetCollectorWin", "All Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.assembly_checkBox.setText(QtGui.QApplication.translate("AssetCollectorWin", "Load Assembly Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.autoCopy_checkBox.setText(QtGui.QApplication.translate("AssetCollectorWin", "Automatic copy after load", None, QtGui.QApplication.UnicodeUTF8))
        self.autoSave_checkBox.setText(QtGui.QApplication.translate("AssetCollectorWin", "Auto Save List", None, QtGui.QApplication.UnicodeUTF8))
        self.save_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Save List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AssetCollectorWin", "Destination : ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPath_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_pushButton.setText(QtGui.QApplication.translate("AssetCollectorWin", "Copy", None, QtGui.QApplication.UnicodeUTF8))

